# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r		 
cache: packages	

matrix:
  include:
    ### build QGIS DEV on macOS
    - os: osx
      latex: false
      sudo: false
      env: mac=true
      install: R -q -e 'tic::install()'
      after_install: R -q -e 'tic::after_install()'
      script: R -q -e 'tic::script()'

before_install:
  #############
  # OSX
  #############
  
  # tap osgeo4mac tap
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew tap osgeo/osgeo4mac; fi
   
  # install saga-gis-lts
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew unlink proj && brew unlink libgeotiff && brew unlink libspatialite && brew unlink postgresql && brew unlink gdal && brew unlink postgis; fi
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew install saga-gis-lts && brew link saga-gis-lts --force; fi
  
  # we need python2
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew install python@2; fi
  # install required python packages
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then pip2 install --user psycopg2 future matplotlib pyparsing gdal pyyaml jinja2 owslib pygments; fi
  
    # Solve gfortran conflict
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then sudo rm -rf /usr/local/gfortran/bin/gfortran && sudo rm /usr/local/include/c++; fi
  # install grass7 and unlink it so that the QGIS linking later on works
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew install grass7 && brew unlink grass7; fi
  # install qgis2
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew install qgis-ltr@2; fi
  
  
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew link --overwrite --force gdal2; fi
  - R -q -e 'install.packages("remotes"); remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages(); tic::before_install()'
  
# imitate a X virtual display -> https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
before_script:
  - "export DISPLAY=:99.0"
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok )& fi
  - sleep 3 # give xvfb some time to start
  
notifications:
  slack:
      rooms:
        - giscience-fsu:3GsmuFR1hkVOUHOPwdra8NXG #rqgis
  on_success: change # default: always
  on_failure: change # default: always
  email: false
